### ISSUE TITLE
[BUG]: liveness probe for healthcheck fails

### ISSUE THREAD

**Issue by sujituk** [NVIDIA-AI-Blueprints/digital-human#28]
### Version

main branch

### Describe the bug.

Background: 
Setting up digital human blueprint using NIMs listed here: https://build.nvidia.com/nvidia/digital-humans-for-customer-service/blueprintcard. 
NIM: nvidia/audio2face-2d with image: `nvcr.io/nim/nvidia/maxine-audio2face-2d:latest`

Issue: 
The container is up and running but the liveness probe `/v1/health/ready` fails consistently.

Sample yaml config for probe:
```
        livenessProbe:
          httpGet:
            path: /v1/health/ready
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 20
          periodSeconds: 10
          failureThreshold: 100
```

Workaround:
Commented the liveness probe to skip healthcheck. 

### Minimum reproducible example

```shell

```

### Relevant log output

```shell

```

### Full env printout

```shell

```

### Code of Conduct

- [x] I agree to follow __THIS PROJECT__'s Code of Conduct
- [x] I have searched the [open bugs](https://github.com/jarmak-nv/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report
